### ISSUE TITLE
upkeep: can this be superseded by `workflow.factset` or is this still relevant?

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/factset_data_loader#14]
@AlexAxthelm is this specifically to load the FactSet data? 

Feel free to close this issue if this repo is still active/ useful.

**Comment by AlexAxthelm** [comment]
This is a non-R utility that is used as an upstream dependency for workflow.factset. I'm maintaining it independently of workflow.factset with the idea that there is utility in having this for non-R users ( @tposey28 )
